### ISSUE TITLE
Unable to resolve relative paths in bootstrap-stylus

### ISSUE THREAD

**Issue by renehamburger** [walmartlabs/stylus-relative-loader#14]
I'm trying to import [bootstrap-stylus](https://github.com/maxmx/bootstrap-stylus) and am surprised that the relative font paths aren't working.

I've added the bootstrap-stylus folder to the loader's path via `stylus-relative-loader?paths=node_modules/bootstrap-styl/` and am able import bootstrap's [index.styl](https://github.com/maxmx/bootstrap-stylus/blob/master/bootstrap/index.styl) as well as all but one dependency successfully with `@import 'bootstrap'`. But loading the font files through the relative path `../fonts/` in [glyphicons.styl](https://github.com/maxmx/bootstrap-stylus/blob/7cdd04645731d5cca885a8467f0a9dcfd62756a4/bootstrap/glyphicons.styl#L13) then fails.

There is a quick fix for this, as the path can be set before importing bootstrap, but I'm sure I'll run into similar issues again. Do you have any idea why this particular relative path doesn't resolve correctly?

**Comment by exogen** [comment]
@renehamburger As far as I know, `url(...)` uses a slightly different code path to resolve files, and by default `stylus-loader` (and also `stylus-relative-loader`) will not resolve them at compile time, but rather leave them alone for the browser to resolve at runtime. I think you can change this with the `resolve url` option to the loader, although I've never tried it. Try setting `?resolve url=true` (or if you're using a query object, `{ "resolve url": true }`.

**Comment by renehamburger** [comment]
Yes, thanks, that works perfectly!
I was expecting this to be implemented by Stylus (equivalent to the '--resolve-url' command line argument), but it's actually implemented by stylus-(relative-)loader [directly](https://github.com/walmartlabs/stylus-relative-loader/blob/master/index.js#L86).

**Comment by uglow** [comment]
@renehamburger were you using Webpack 1 or 2? I can get Bootstrap-Stylus to work with Webpack 1 (as you described), but not in Webpack 2.
