### ISSUE TITLE
syntax error which breaks the loader

### ISSUE THREAD

**Issue by ruben-grossmann** [walmartlabs/stylus-relative-loader#17]
https://github.com/walmartlabs/stylus-relative-loader/blob/d797a98bc48aa68d6b51ad11201603d1c35dfc27/index.js#L32

Can you please remove the `this` ?
This way, i can't use the loader, because it crashes.

**Comment by ryan-roemer** [comment]
It looks like a webpack-pre-4 to webpack-post-4 thing. I'm not sure the folks in this project intend to drop webpack-pre-4, so perhaps a PR along the lines of what the upstream project this is forked form would be appropriate https://github.com/shama/stylus-loader/commit/fc81e32e684dc95832d5ef0f24703265d1e132f6

**Comment by ruben-grossmann** [comment]
@ryan-roemer Thanks for the answer and the commit reference. I will do this.
